apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
# https://github.com/argoproj/argo-cd/blob/v2.4.6/manifests/ha/install.yaml
